FEATURE Customize voicebot messages
VOIQ/VOIQ-LiveChatSetupFE pull request #36
Opened 2021-01-12 17:19 UTC by dieguischa

2021-01-12 22:22 UTC, DanielOlarte requested changes

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/BubbleMessages.jsx
> +            id={"known visitor message"}
@dieguischa ID should not have spaces, use something like known-visitor-message

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/BubbleMessages.jsx
> +            error id="standard-error"
@dieguischa You could use the inputProps from material-ui to set the maxlength and avoid this extra validation. 

`inputProps={{
          maxlength: 100
        }}`

And also, you can put the character count in the helperText such as helperText="knownVisitorMessage.length/MAX_CHARACTERS" and it will update with the onChange.

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/BubbleMessages.jsx
> +export default BubbleMessages;
@dieguischa Add extra line to avoid issues with ending lines

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/Customize.jsx
> +  const setKnownVisitorMessage = props.setKnownVisitorMessage;
@dieguischa Why don't you pass the props directly to the component? Any specific reason to have a const created here?

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/Customize.scss
> +.customize-text-area{
@dieguischa Spacing and maybe create a custom class for width: 100% important! that can be reused easily

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/Customize.scss
> +}
@dieguischa Add extra line to avoid issues with ending lines

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/ExampleQuestions.jsx
> +const ExampleQuestions = (props) => {
@dieguischa I reviewed this component and it's very similar to the Answers component. Is there a way to create a component to easily reuse this type of UI module, maybe we could do it now when we don't have a lot of UI, what do you think @juan-voiq ?

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/ExampleQuestions.jsx
> +        {numberOfQuestions<3 && (
@dieguischa Spacing

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/Instructions.jsx
> +  let error = false;
@dieguischa If it's always false, why do you need this and the extra validation, also, we need to add a new character limit here of 100.

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/QuestionRow.jsx
> +  let error = (questionText.length>60) ? true : false;
@dieguischa Spacing

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/QuestionRow.jsx
> +            console.log(question);
@dieguischa unused console.log

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/QuestionRow.jsx
> +            return question;
@dieguischa Simplify the multiple returns, and remove the else given that you always return question

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/QuestionRow.jsx
> +      {error ? (
@dieguischa Same as before

2021-01-12 22:22 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/QuestionRow.jsx
> +export default QuestionRow;
@dieguischa Add extra line to avoid issues with ending lines

2021-01-12 22:22 UTC, DanielOlarte commented on src/services/ExampleQuestionService.js
> +    config.apiUrl + "/api/example_questions/"+voicebotId
@dieguischa Spacing

2021-01-13 17:32 UTC, juan-voiq requested changes
Just a couple of details

2021-01-13 17:32 UTC, juan-voiq commented on src/components/Voicebots/EditVoicebot/Setup/Customize/BubbleMessages.jsx
> +        // TODO: Handle response?
Is this TODO from a copy paste?

2021-01-13 17:32 UTC, juan-voiq commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/ExampleQuestions.jsx
> +const ExampleQuestions = (props) => {
If it is possible always a +1 for reusability.

2021-01-13 17:32 UTC, juan-voiq commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/Instructions.jsx
> +        // TODO: Handle response?
Same :point_up:

2021-01-13 17:32 UTC, juan-voiq commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/QuestionRow.jsx
> +          id={`${props.question.id}`}
Is this interpolation necessary?

2021-01-13 17:32 UTC, juan-voiq commented on src/components/Voicebots/EditVoicebot/Setup/Setup.jsx
> +
Styling

2021-01-13 18:14 UTC, dieguischa commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/ExampleQuestions.jsx
> +const ExampleQuestions = (props) => {
I think there is a few items that differ like the cloud Icon and the constraint of the number of items in the table, however it would be possible.

2021-01-13 18:53 UTC, DanielOlarte requested changes

2021-01-13 18:53 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/BubbleMessages.jsx
> +  const voicebotId = props.voicebotId;
@dieguischa Why did you create these constants instead of using the props directly?

2021-01-13 18:53 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/BubbleMessages.jsx
> +          helperText={knownVisitorMessage.length+"/"+maxLength}
@dieguischa Styling

2021-01-13 18:53 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/ExampleQuestions.jsx
> +    setNumberOfQuestions(numberOfQuestions+1);
@dieguischa Spacing

2021-01-13 18:53 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/ExampleQuestions.jsx
> +  const [questions, setExampleQuestions] = useState("[]");
@dieguischa Why a string?

2021-01-13 18:53 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/Instructions.jsx
> +          helperText={instructions.length+"/"+maxLength}
@dieguischa Spacing

2021-01-13 18:53 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/QuestionRow.jsx
> +          helperText={questionText.length+"/"+maxLength}
@dieguischa Spacing

2021-01-14 15:08 UTC, dieguischa commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/ExampleQuestions.jsx
> +  const [questions, setExampleQuestions] = useState("[]");
Because on setExampleQuestions we use `JSON.stringify(response)`

2021-01-14 20:54 UTC, DanielOlarte requested changes

2021-01-14 20:54 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/VoicebotImage.jsx
> +  const voicebotId = props.voicebotId;
@dieguischa Can you update this?

2021-01-14 20:54 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/ItemRow.jsx
> +import React, {useState} from "react";
@dieguischa We should move this component to another folder that can be easily reused in different parts of the application, instead of nesting it inside Setup

2021-01-14 20:54 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/ItemRow.jsx
> +          id={`${props.item.id}`}
@dieguischa Do we need the interpolation?

2021-01-14 20:54 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/ItemRow.jsx
> +      { props.cloudIcon &&
@dieguischa This seems very custom to the audio_id of the answers component, maybe, we can pass a function to this component instead of doing it here?

2021-01-14 20:54 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Train/StandardFaqs/Answers.jsx
> +        console.log(response);
@dieguischa Remove these console.log

2021-01-14 20:54 UTC, DanielOlarte commented on src/services/ExampleQuestionService.js
> +      id: questionId,
@dieguischa Why do you send the id if you already have it in the URL?

2021-01-14 20:54 UTC, DanielOlarte commented on src/services/ExampleQuestionService.js
> +      "voicebot_id": voicebotId,
@dieguischa Why do you send the id if you already have it in the URL?

2021-01-14 20:57 UTC, dieguischa commented on src/components/Voicebots/EditVoicebot/Setup/ItemRow.jsx
> +          id={`${props.item.id}`}
Yes, since the answer doesn't have the constraint of length, it's there for longer entitites that couldn't fit in a smaller ItemRow

2021-01-14 21:01 UTC, dieguischa commented on src/services/ExampleQuestionService.js
> +      id: questionId,
That's what wasn't adding up at first, now I get it...

2021-01-14 21:27 UTC, dieguischa commented on src/components/Voicebots/EditVoicebot/Setup/ItemRow.jsx
> +      { props.cloudIcon &&
Since that updated attribute is linked to an Item, it's complicated but I'm working on it

2021-01-15 16:21 UTC, DanielOlarte requested changes

2021-01-15 16:21 UTC, DanielOlarte commented on src/components/Utils/ItemTable.jsx
> +              JSON.parse(props.itemList) && JSON.parse(props.itemList).map((item, index) => (
@dieguischa I think we can put this JSON.parse before the return like: _const items = JSON.parse(props.itemList);_ and also, we could add this callback when we use that ItemTable (suggestion)

```
iconStatusCallback={(items, item, index, updated) => {return <Grid item xs={1} audio_id={item.audio_id}>
          { items[index].audio_id && !updated && <CloudDoneIcon /> }
        </Grid>})}
```
        
And in ItemRow:

`iconStatusCallback={() => {return props.iconStatusCallback(items, item, index, props.updated})}
`
Not entirely sure if it works, you can try it out and let me know if it makes sense and if it works.

2021-01-15 16:21 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/ExampleQuestions.jsx
> +        console.log(response);
@dieguischa Let's remove these console.logs

2021-01-15 16:21 UTC, DanielOlarte commented on src/components/Utils/ItemTable.jsx
> +        {( (props.numberOfItems < props.limit) || !props.limit ) && (
@dieguischa Let's put a default value at the top of the function if the props.limit it's not present to avoid this double validation.

2021-01-15 16:21 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Train/StandardFaqs/Answers.jsx
> +            console.log(answer);
@dieguischa Remove this

2021-01-15 16:32 UTC, dieguischa commented on src/components/Utils/ItemRow.jsx
> +          id={`${props.item.id}`}
Sorry, I thougth you ment the other lines, that came from a Copy Paste, i'll delete it.

2021-01-15 16:44 UTC, dieguischa commented on src/components/Utils/ItemRow.jsx
> +          id={`${props.item.id}`}
If the id is a number a Warning pops up:

`Warning: Failed prop type: Invalid prop `id` of type `number` supplied to `ForwardRef(InputBase)`, expected `string``

2021-01-15 17:09 UTC, DanielOlarte commented on src/components/Utils/ItemRow.jsx
> +          id={`${props.item.id}`}
Ok, maybe add a prefix like item-{props.item.id}?

2021-01-15 17:23 UTC, dieguischa commented on src/components/Utils/ItemRow.jsx
> +          id={`${props.item.id}`}
But then we'd have to do some changes in the OnBlur methods because we use that `target.event.id`

2021-01-18 16:29 UTC, juan-voiq commented on src/components/Utils/ItemTable.jsx
> +              JSON.parse(props.itemList) && JSON.parse(props.itemList).map((item, index) => (
@dieguischa Did you check this comment?

2021-01-18 16:32 UTC, dieguischa commented on src/components/Utils/ItemTable.jsx
> +              JSON.parse(props.itemList) && JSON.parse(props.itemList).map((item, index) => (
Yes, that was the suggested solution but we went a different direction with the `shouldShowOptionalIconList` on the Answer Component

2021-01-18 16:57 UTC, DanielOlarte requested changes

2021-01-18 16:57 UTC, DanielOlarte commented on src/components/Utils/ItemRow.jsx
> +          id={`${props.item.id}`}
Yes, that's ok, let's do it.

2021-01-18 16:57 UTC, DanielOlarte commented on src/components/Utils/ItemTable.jsx
> +              JSON.parse(props.itemList) && JSON.parse(props.itemList).map((item, index) => (
But you could still store this _const items = JSON.parse(props.itemList);_ to avoid that double parsing.

2021-01-18 16:57 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Customize/FrameMessages/ExampleQuestions.jsx
> +      (response) => {
@dieguischa Why an empty callback?

2021-01-18 16:57 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Train/StandardFaqs/Answers.jsx
> +  useEffect(() => {
@dieguischa Why don't you do this processing when the answers change instead of creating a new array for that? e.g., you can loop over the props.answers and set the should_show_optional_icon=true|false inside the props.answers itself, in this way, you don't need the extra array and you can simply loop over the answers JSON to know if we should display the icon.

2021-01-18 17:12 UTC, dieguischa commented on src/components/Utils/ItemRow.jsx
> +          id={`${props.item.id}`}
Does `""+props.item.id` work?

2021-01-18 17:39 UTC, dieguischa commented on src/components/Voicebots/EditVoicebot/Setup/Train/StandardFaqs/Answers.jsx
> +  useEffect(() => {
You mean assign an additional property to each item on the props.items list?

2021-01-18 17:49 UTC, DanielOlarte commented on src/components/Voicebots/EditVoicebot/Setup/Train/StandardFaqs/Answers.jsx
> +  useEffect(() => {
Yes

2021-01-18 17:54 UTC, DanielOlarte commented on src/components/Utils/ItemRow.jsx
> +          id={`${props.item.id}`}
To avoid special syntax in CSS (if we ever have to style by ID), let's start with letters and then, the ID, like I told you before.

2021-01-19 17:14 UTC, juan-voiq approved these changes

2021-01-19 18:43 UTC, merged