(WIP) FEATURE My profile
VOIQ/VOIQ-LiveChatSetupFE pull request #37
Opened 2021-01-19 21:33 UTC by dieguischa

2021-01-21 17:04 UTC, juan-voiq commented on src/components/Account/BasicInfo.jsx
> +  const namesMaxLength = 40;
If these are constants can you put them in the constants file

2021-01-21 17:05 UTC, juan-voiq commented on src/components/Account/BasicInfo.jsx
> +  const namesMaxLength = 40;
Oops sorry thought we had one like in the setup-fe, can you create one?

2021-01-21 20:28 UTC, DanielOlarte requested changes

2021-01-21 20:28 UTC, DanielOlarte commented on src/components/Account/BasicInfo.jsx
> +          first_name: event.target.value.trim()
@dieguischa We could trim the value before the switch

2021-01-21 20:28 UTC, DanielOlarte commented on src/components/Account/BasicInfo.jsx
> +        console.log("ERROR")
@dieguischa What kind of error can we display here to make it more clear?

2021-01-21 20:28 UTC, DanielOlarte commented on src/components/Account/BasicInfo.jsx
> +              console.log("ERROR");
@dieguischa Same here

2021-01-21 20:28 UTC, DanielOlarte commented on src/components/Account/BasicInfo.jsx
> +        setFirstName(event.target.value);
@dieguischa Maybe define the value before the switch

2021-01-21 20:28 UTC, DanielOlarte commented on src/components/Account/BasicInfo.jsx
> +        console.log("ERROR");
@dieguischa Same here

2021-01-21 20:28 UTC, DanielOlarte commented on src/components/Account/BasicInfo.jsx
> +            label={errorText}
@dieguischa Could we reduce this if into a single statement?

2021-01-22 16:07 UTC, DanielOlarte requested changes

2021-01-22 16:07 UTC, DanielOlarte commented on src/components/Account/BasicInfo.jsx
> +        console.log("Not a valid ID");
@dieguischa Can you be more specific?

2021-01-22 16:07 UTC, DanielOlarte commented on src/components/Account/BasicInfo.jsx
> +              console.log("Not a valid ID");
@dieguischa Can you be more specific?

2021-01-22 16:07 UTC, DanielOlarte commented on src/constants.js
> +export const MAX_LEN_COMPANY_NAME  = 50;
@dieguischa Fix spacing

2021-01-22 16:49 UTC, DanielOlarte commented on src/components/Account/BasicInfo.jsx
> +        console.log("ERROR: Unrecognised case " + event.target.id);
@dieguischa Improve the logging, it would be useful to know where this error happened easily instead of navigate through the trace.

2021-01-22 18:42 UTC, DanielOlarte approved these changes

2021-01-22 18:43 UTC, merged