Feature custom messages&questions
VOIQ/VOIQ-LiveChatSetupFE pull request #38
Opened 2021-01-29 20:28 UTC by dieguischa

2021-01-29 20:29 UTC, juan-voiq approved these changes

2021-02-01 13:00 UTC, DanielOlarte requested changes

2021-02-01 13:00 UTC, DanielOlarte commented on src/constants.js
> +export const MAX_LEN_QUESTION = 60;
@dieguischa can you put more specific names to avoid future confusions?

2021-02-01 21:47 UTC, DanielOlarte approved these changes

2021-02-01 21:58 UTC, merged