Fix generate response
VOIQ/VOIQ-LiveChatSetupFE pull request #42
Opened 2021-03-02 22:01 UTC by dieguischa

2021-03-03 20:45 UTC, juan-voiq requested changes
Just a styling question

2021-03-03 20:45 UTC, juan-voiq commented on src/components/Voicebots/EditVoicebot/Setup/Setup.jsx
> +            setActivationAlertMessage("Activation completed with " + response.errors + " errors.");
What's the standard in styling for concatenation, in my opinion it looks cleaner with interpolation: 'asdasd ${qwe}'

2021-03-03 21:33 UTC, dieguischa commented on src/components/Voicebots/EditVoicebot/Setup/Setup.jsx
> +            setActivationAlertMessage("Activation completed with " + response.errors + " errors.");
@juan-voiq lets keep interpolation instead of concatenation, for consistency and per: https://github.com/airbnb/ruby >> Strings

2021-03-03 21:43 UTC, dieguischa commented on src/components/Voicebots/EditVoicebot/Setup/Setup.jsx
> +            setActivationAlertMessage("Activation completed with " + response.errors + " errors.");
@juan-voiq Per: https://github.com/airbnb/javascript it is cleaner to use template-curly-spacing.

2021-03-03 23:29 UTC, DanielOlarte requested changes

2021-03-04 14:30 UTC, DanielOlarte approved these changes

2021-03-04 14:30 UTC, merged