Feature fa qs custom training
VOIQ/VOIQ-LiveChatSetupFE pull request #46
Opened 2021-03-11 20:08 UTC by dieguischa

2021-03-11 22:02 UTC, DanielOlarte requested changes
Let's use the correct nesting for the new routes (api/voicebots/:voicebot_id) because in some of the new endpoints for intents you have the new format and others have the older format

2021-03-12 17:13 UTC, DanielOlarte approved these changes

2021-03-12 17:37 UTC, juan-voiq requested changes
Couple of small changes

2021-03-12 17:37 UTC, juan-voiq commented on src/components/Utils/ItemRow.jsx
> +      return item.length + "/" + props.maxLength;
Lets use interpolation please, it is easier to read

2021-03-12 17:37 UTC, juan-voiq commented on src/components/Voicebots/EditVoicebot/Setup/Train/TrainingMaterial/Examples.jsx
> +      event.target.id.split('-')[1],
This splitting its a little obscure, can we create a helper function with a comment that explains why it is the second item of the splitted string?

2021-03-12 19:19 UTC, merged