Added train button to download zip file
VOIQ/VOIQ-LiveChatSetupFE pull request #47
Opened 2021-03-11 20:19 UTC by DanielOlarte

2021-03-11 21:00 UTC, dieguischa requested changes

2021-03-11 21:00 UTC, dieguischa commented on src/components/Voicebots/EditVoicebot/Setup/Setup.jsx
> +import VoicebotResponsesService from '../../../../services/VoicebotTrainingService';
@DanielOlarte The voicebot activation service has to be imported.

2021-03-12 14:07 UTC, dieguischa approved these changes

2021-03-12 17:14 UTC, juan-voiq approved these changes

2021-03-12 17:14 UTC, merged