Create voicebot
VOIQ/VOIQ-LiveChatSetupFE pull request #71
Opened 2021-04-28 22:42 UTC by dieguischa

2021-04-28 22:46 UTC, juan-voiq approved these changes

2021-04-29 00:06 UTC, DanielOlarte requested changes
Make sure that the FAQs panel is available (even if they don't have FAQs yet) so they can create or upload a file.

2021-04-29 00:06 UTC, DanielOlarte commented on src/components/Voicebots/CreateVoicebot/CreateVoicebot.jsx
> +        for (const user of response) {
@dieguischa We should ignore the Super Admin user (it shouldn't have a bot associated to it)

2021-04-29 00:06 UTC, DanielOlarte commented on src/components/Voicebots/CreateVoicebot/CreateVoicebot.jsx
> +      console.error(e);
@dieguischa We should display an error message to the user if this happens

2021-04-29 00:06 UTC, DanielOlarte commented on src/components/Voicebots/CreateVoicebot/CreateVoicebot.jsx
> +      console.error(e);
@dieguischa Same here

2021-04-29 00:06 UTC, DanielOlarte commented on src/services/UsersService.js
> +
@dieguischa Remove extra space

2021-04-29 15:28 UTC, DanielOlarte approved these changes

2021-04-29 15:28 UTC, merged