Select voice & preview voice
VOIQ/VOIQ-LiveChatSetupFE pull request #86
Opened 2021-05-07 20:09 UTC by dieguischa

2021-05-07 21:18 UTC, DanielOlarte requested changes

2021-05-07 21:18 UTC, DanielOlarte commented on src/components/Voicebots/CreateVoicebot/CreateVoicebot.jsx
> +            break;
@dieguischa Spacing

2021-05-07 21:18 UTC, DanielOlarte commented on src/components/Voicebots/CreateVoicebot/CreateVoicebot.jsx
> +
@dieguischa Spacing

2021-05-07 21:18 UTC, DanielOlarte commented on src/components/Utils/PreviewAudio.jsx
> +                        props.playingRef.current.play();
@dieguischa Let's create a function for this callback.

2021-05-07 22:17 UTC, DanielOlarte approved these changes

2021-05-10 16:28 UTC, juan-voiq approved these changes

2021-05-10 16:28 UTC, merged